version: '3.8'

services:
  coda-upload:
    build: .
    container_name: coda-upload
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - web

networks:
  web:
    external: true
